### **IMPORT LIBRARY**

In [58]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [59]:

dict1 ={'Name':['Priyang','Aadhya','Krisha','Vedant','Parshv',
                'Mittal','Archana'],
                'Marks':[98,89,99,87,90,83,99],
                'Gender':['Male','Female','Female','Male','Male',
                         'Female','Female']
               }
df=pd.DataFrame(dict1)
df

      Name  Marks  Gender
0  Priyang     98    Male
1   Aadhya     89  Female
2   Krisha     99  Female
3   Vedant     87    Male
4   Parshv     90    Male
5   Mittal     83  Female
6  Archana     99  Female

### ***TOP 3***

In [60]:
df.head(3)

      Name  Marks  Gender
0  Priyang     98    Male
1   Aadhya     89  Female
2   Krisha     99  Female

### **LAST 3***

In [61]:
df.tail(3)

      Name  Marks  Gender
4   Parshv     90    Male
5   Mittal     83  Female
6  Archana     99  Female

### **SHAPE**

In [62]:
df.shape

(7, 3)

In [63]:
print("NUMBER OF ROWS:",df.shape[0])
print("NUMBER OF COLUMNS:",df.shape[1])

NUMBER OF ROWS: 7
NUMBER OF COLUMNS: 3

### **INFORMATION**

In [64]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    7 non-null      object
 1   Marks   7 non-null      int64
 2   Gender  7 non-null      object
dtypes: int64(1), object(2)
memory usage: 300.0+ bytes

### **NULL**

In [65]:
df.isnull().sum()

Name      0
Marks     0
Gender    0
dtype: int64

In [66]:
df.isnull().sum(axis=1)

0    0
1    0
2    0
3    0
4    0
5    0
6    0
dtype: int64

### **STATISTICS**

In [67]:
df.describe()

           Marks
count   7.000000
mean   92.142857
std     6.491753
min    83.000000
25%    88.000000
50%    90.000000
75%    98.500000
max    99.000000

In [68]:
df.describe(include='all')

           Name      Marks  Gender
count         7   7.000000       7
unique        7        NaN       2
top     Priyang        NaN  Female
freq          1        NaN       4
mean        NaN  92.142857     NaN
std         NaN   6.491753     NaN
min         NaN  83.000000     NaN
25%         NaN  88.000000     NaN
50%         NaN  90.000000     NaN
75%         NaN  98.500000     NaN
max         NaN  99.000000     NaN

### **UNIQUE**

In [69]:
df['Gender'].unique()

array(['Male', 'Female'], dtype=object)

In [70]:
df['Gender'].nunique()

2

### **Count**

In [71]:
df['Gender'].value_counts()

Gender
Female    4
Male      3
Name: count, dtype: int64

### **Between**

In [72]:
df[df['Marks']>=90]

      Name  Marks  Gender
0  Priyang     98    Male
2   Krisha     99  Female
4   Parshv     90    Male
6  Archana     99  Female

In [73]:
df[(df['Marks']>=80) & (df['Marks']<=95)]

     Name  Marks  Gender
1  Aadhya     89  Female
3  Vedant     87    Male
4  Parshv     90    Male
5  Mittal     83  Female

In [74]:
df[df['Marks'].between(90,100)]

      Name  Marks  Gender
0  Priyang     98    Male
2   Krisha     99  Female
4   Parshv     90    Male
6  Archana     99  Female

### **AVERAGE**

In [75]:
df['Marks'].mean()

92.14285714285714

### **APPLY**

In [76]:
def marks(x):
    return x//2

In [77]:
df['Half_marks'] =df['Marks'].apply(marks)
df

      Name  Marks  Gender  Half_marks
0  Priyang     98    Male          49
1   Aadhya     89  Female          44
2   Krisha     99  Female          49
3   Vedant     87    Male          43
4   Parshv     90    Male          45
5   Mittal     83  Female          41
6  Archana     99  Female          49

In [78]:
df['Add_humdred']=df['Marks'].apply(lambda x:x+100)
df

      Name  Marks  Gender  Half_marks  Add_humdred
0  Priyang     98    Male          49          198
1   Aadhya     89  Female          44          189
2   Krisha     99  Female          49          199
3   Vedant     87    Male          43          187
4   Parshv     90    Male          45          190
5   Mittal     83  Female          41          183
6  Archana     99  Female          49          199

### **MAP**

In [79]:
df['Male_Female']=df['Gender'].map({'Male':1, 'Female':0})
df

      Name  Marks  Gender  Half_marks  Add_humdred  Male_Female
0  Priyang     98    Male          49          198            1
1   Aadhya     89  Female          44          189            0
2   Krisha     99  Female          49          199            0
3   Vedant     87    Male          43          187            1
4   Parshv     90    Male          45          190            1
5   Mittal     83  Female          41          183            0
6  Archana     99  Female          49          199            0

### **Drop the columns**

In [80]:
df.drop('Male_Female', axis=1)

      Name  Marks  Gender  Half_marks  Add_humdred
0  Priyang     98    Male          49          198
1   Aadhya     89  Female          44          189
2   Krisha     99  Female          49          199
3   Vedant     87    Male          43          187
4   Parshv     90    Male          45          190
5   Mittal     83  Female          41          183
6  Archana     99  Female          49          199

In [81]:
df.drop(['Male_Female', 'Add_humdred'], axis=1)

      Name  Marks  Gender  Half_marks
0  Priyang     98    Male          49
1   Aadhya     89  Female          44
2   Krisha     99  Female          49
3   Vedant     87    Male          43
4   Parshv     90    Male          45
5   Mittal     83  Female          41
6  Archana     99  Female          49

### **Columns**

In [82]:
df.columns

Index(['Name', 'Marks', 'Gender', 'Half_marks', 'Add_humdred', 'Male_Female'], dtype='object')

In [83]:
df.index

RangeIndex(start=0, stop=7, step=1)

### **Sort**

In [84]:
df.sort_values(by = 'Marks')

      Name  Marks  Gender  Half_marks  Add_humdred  Male_Female
5   Mittal     83  Female          41          183            0
3   Vedant     87    Male          43          187            1
1   Aadhya     89  Female          44          189            0
4   Parshv     90    Male          45          190            1
0  Priyang     98    Male          49          198            1
2   Krisha     99  Female          49          199            0
6  Archana     99  Female          49          199            0